version: '3.8'
services:
  postgres:
    image: postgres:15.4
    container_name: lab7-postgres
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_DB=lab7
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - pg-data-local:/var/lib/postgresql/data_local


  interwise:
    container_name: inteerw
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8091:8091"
    volumes:
      - ./docs:/app/docs
    environment:
      SWAGGER_JSON: /home/udainoko/Documents/BSUIR/Sem4/OOP/Lab7/docs/swagger.json
    env_file:
        - .env
    depends_on:
        - postgres
    restart: always

volumes:
    pg-data-local: