<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.3.26207.106" />
      <PackageReference Include="System.ServiceProcess.ServiceController" Version="11.0.0-preview.3.26207.106" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CarSeller.Domain\CarSeller.Domain.csproj" />
    </ItemGroup>

</Project>
