definitions:
  models.AnyUserInfo:
    properties:
      email:
        type: string
      username:
        type: string
    type: object
  models.Credentials:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.RegisterInfo:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  title: Interwier
  version: "1.0"
paths:
  /api/candidates:
    post:
      consumes:
      - application/json
      description: Создаёт кандидата в защищённой зоне
      parameters:
      - description: Candidate info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.AnyUserInfo'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - PASETOAuth: []
      summary: Добавить кандидата (требует PASETO токен)
      tags:
      - candidates
  /login:
    post:
      consumes:
      - application/json
      description: Login user and return pasetto tocken
      parameters:
      - description: Sign in info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Login user
      tags:
      - log in
  /register:
    post:
      consumes:
      - application/json
      description: Returns nil error of success
      parameters:
      - description: Sign in info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RegisterInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Register user
      tags:
      - sign in
securityDefinitions:
  PASETOAuth:
    description: Введите "Bearer <PASETO токен>". Получите токен на /login и прикрепите
      его.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
